---
title: "Project_2_Data_624"
author: "Farhod Ibragimov, Alexander Simon, Jackie Yee, Mubashira Qari"
date: "2026-04-18"
output:
  html_document:
    toc: true
    toc_float: true
  word_document:
    toc: true
---

=====================================================
**Loading Datasets**
=====================================================

```{r message=FALSE, warning=FALSE}

# Load libraries
library(tidyverse)
library(mice)      # For advanced imputation
library(caret)     # For data splitting and pre-processing

# Load the datasets
train_data <- read.csv("https://raw.githubusercontent.com/uzmabb182/Data_624_Team_Project_2/refs/heads/main/StudentData.csv", stringsAsFactors = FALSE)

eval_data <- read.csv("https://raw.githubusercontent.com/uzmabb182/Data_624_Team_Project_2/refs/heads/main/StudentEvaluation.csv", stringsAsFactors = FALSE)


#view(train_data)
view(eval_data)
```

=====================================================
**Data Exploration (EDA)**
=====================================================

```{r}

```


```{r}

```

=====================================================
**Data Preparation (eg, imputation, transformations)**
=====================================================

```{r}

```

